
Vagrant.configure(2) do |config|
	config.vm.provision "shell", inline: "echo Hello all!"
	
	config.vm.define "FTP" do |ftp|
		ftp.vm.box = "centos/7"
		ftp.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		ftp.vm.network "private_network", ip: "10.10.10.200"
		ftp.vm.provision "shell", inline: "echo FTP is UP!"
		ftp.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end

	config.vm.define "WEB" do |web|
		web.vm.box     = "ubuntu/trusty64"
		web.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		web.vm.network "private_network", ip: "10.10.10.100"
                web.vm.provision "shell", inline: "echo Web is UP!"
		web.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end

        config.vm.define "DOC" do |doc|
                doc.vm.box     = "ubuntu/trusty64"
                doc.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
                doc.vm.network "private_network", ip: "10.10.10.150"
		doc.vm.provision "shell", inline: "echo Docker_machine is UP!"
		doc.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
        end

        config.vm.define "LIN" do |lin|
                lin.vm.box     = "akost/linux-mint-17-kde"
                lin.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
                lin.vm.network "private_network", ip: "10.10.10.50"
		lin.vm.provision "shell", inline: "echo LinuxMint is UP!"
		lin.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
        end
	
	config.vm.define "CHEF" do |chef|
		chef.vm.box = "centos/7"
		chef.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		chef.vm.network "private_network", ip: "10.10.10.250"
		chef.vm.provision "shell", inline: "echo CHEF is UP!"
		chef.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end
	
	config.vm.define "ANS" do |ans|
		ans.vm.box = "centos/7"
		ans.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		ans.vm.network "private_network", ip: "10.10.10.25"
		ans.vm.provision "shell", inline: "echo ANS is UP!"
		ans.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end

	config.vm.define "MAN" do |man|
		man.vm.box = "centos/7"
		man.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		man.vm.network "private_network", ip: "10.10.10.75"
		man.vm.provision "shell", inline: "echo Manager is UP"
		man.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end

	config.vm.define "NGINX" do |ngnx|
		ngnx.vm.box     = "centos/7"
		ngnx.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "eth0"
		ngnx.vm.network "private_network", ip: "10.10.10.125"
                ngnx.vm.provision "shell", inline: "echo NGINX is UP!"
		ngnx.vm.synced_folder "/home/ikohut/git_folder", "/host_share"
	end

end
